version: '2'

services:
  nginx:
    build: ${DOCKER_CONFIG_PATH}/nginx
    container_name: nginx
    links:
      - node-api:node-api
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTP_PORT_SSL}:443"
    depends_on:
      - node-api
    volumes:
      - ${DOCKER_CONFIG_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_DATA_PATH}/logs/nginx:/var/log/nginx
    restart: on-failure:5

  node-api:
    build: ${DOCKER_CONFIG_PATH}/node
    container_name: node-api
    links:
      - mongo:mongo
    depends_on:
      - mongo
    volumes:
      - ${SRC_PATH}:${NODE_PATH}
      - ${DOCKER_DATA_PATH}/logs/node-api:/var/log
      - ${DOCKER_DATA_PATH}/cache/node-api/npm:/usr/local/cache/npm
      - ${DOCKER_DATA_PATH}/cache/node-api/root:/root
    restart: on-failure:5
    environment:
      - NODE_ENV
      - NODE_PORT:5000
      - NODE_PATH

  mongo:
    build: ${DOCKER_CONFIG_PATH}/mongo
    container_name: mongo
    volumes:
      - ${DOCKER_DATA_PATH}/db/mongo:/data/db
      - ${DOCKER_DATA_PATH}/db/mongo-config:/data/configdb
      - ${DOCKER_DATA_PATH}/logs/mongo:/var/log
    restart: on-failure:5