version: '2'

services:
  nginx:
    build: ${PK_DOCKER_CONFIG_PATH}/nginx
    container_name: nginx
    links:
      - app:app
    ports:
      - "${PK_HTTP_PORT}:80"
      - "${PK_HTTP_PORT_SSL}:443"
    depends_on:
      - app
    volumes:
      - ${PK_DOCKER_CONFIG_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${PK_DOCKER_DATA_PATH}/logs/nginx:/var/log/nginx
    restart: on-failure:5

  mongodb:
    build: ${PK_DOCKER_CONFIG_PATH}/mongodb
    container_name: mongodb
    ports:
      - 27017:27017 # process
      - 28017:28017 # http
    volumes:
      - ${PK_DOCKER_DATA_PATH}/db/mongodb/db:/data/db
      - ${PK_DOCKER_DATA_PATH}/db/mongodb/configdb:/data/configdb
      - ${PK_DOCKER_DATA_PATH}/logs/mongodb:/var/log
    restart: on-failure:5
    environment:
      - MONGO_PORT=27017

  app:
    build: ${PK_DOCKER_CONFIG_PATH}/node
    container_name: app
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    volumes:
      - ${PK_SRC_PATH}:${PK_NODE_PATH}
      - ${PK_DOCKER_DATA_PATH}/logs/app:/var/log
      - ${PK_DOCKER_DATA_PATH}/cache/app/npm:/usr/local/cache/npm
      - ${PK_DOCKER_DATA_PATH}/cache/app/root:/root
    restart: on-failure:5
    environment:
      - NODE_ENV=${PK_NODE_ENV}
      - NODE_PATH=${PK_NODE_PATH}
      - NODE_PORT=5000
      - SQLITE_DB=${PK_DOCKER_DATA_PATH}/db/pokedex.sqlite