#!/usr/bin/env bash

source .env

if [ ! -f "pokedex.sqlite" ]
then
    echo "Downloading pokedex.sqlite DB..."
    wget -q https://github.com/metaunicorn/pokedex-data/raw/master/db/database-sqlite.zip
    rm -f pokedex.sqlite
    unzip -q database-sqlite.zip
    rm -f database-sqlite.zip
    mv database.sqlite pokedex.sqlite
fi

if [ -z "${1}" ]
then
    echo "Rebuilding Docker containers..."
else
    echo "Rebuilding Docker containers: ${@}..."
fi

# Destroy and rebuild all docker containers
docker-compose stop $@

# Build and start containers again
docker-compose up -d --build $@

# Show running containers
docker ps
